### ISSUE TITLE
Remove matplotlib from dependancies

### ISSUE THREAD

**Issue by mrava87** [Statoil/pylops#4]
matplotlib is used only within utils.wavelets. Consider removing those plots and free the user version from matplotlib dependency

**Comment by cako** [comment]
I second this. Appears to only be used in one function, and causes issues in systems without tkinter, namely a fresh Ubuntu 18.04 install. (This can be fixed with `sudo apt install python3-tk`)

**Comment by mrava87** [comment]
matplotlib is not anymore a dependency in v1.0.0
